name: "Node Backend Project" 
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./backend
    steps:
      # Step 1: Clone your repository's code onto the virtual machine
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Run a simple terminal command
      - name: Say Hello
        run: echo "The code cloned successfully. Ready to run!"
